networks:
  default:
    name: nginx
    external: true

services:
  timescale:
    image: timescale/timescaledb:2.18.1-pg17
    restart: unless-stopped
    env_file: .env.timescale
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env.backend
    ports:
      - "8001:8001"
    depends_on:
      - timescale

volumes:
  timescale_data:
    driver: local
